DROP TABLE IF EXISTS source_colt.customers;

CREATE TABLE source_colt.customers
(
	id serial,
	building_id varchar,
	s_ocn varchar,
	cust_name varchar,
	man_employee_total decimal,
	db_country_name varchar,
	db_nace_code decimal,
	db_employee_here decimal,
	db_employee_total decimal,
	db_sic_code int,
	db_industry varchar,
	db_industry_level_1 varchar,
	db_industry_level_2 varchar,
	db_industry_level_3 varchar,
	gl_revenue_year_2014 decimal,
	db_duns bigint,
	sfdc_account_name varchar,
	carrier_voice decimal,
	colocation decimal,
	colt_total decimal,
	customer_asset_sales_data decimal,
	customer_asset_sales_managed_services decimal,
	data_centre_services decimal,
	data_centre_services_installation_adjustment decimal,
	data_installation_adjustment decimal,
	dedicated_hosting decimal,
	ethernet_point_to_point decimal,
	ethernet_vpn decimal,
	high_speed_service decimal,
	incoming decimal,
	in_services decimal,
	intercompany_voice decimal,
	internet_access decimal,
	ip_voice decimal,
	ipvpn_corporate decimal,
	link decimal,
	managed_service_installation_adjustment decimal,
	other_bandwidth decimal,
	other_misc_data decimal,
	other_voice decimal,
	professional_services decimal,
	reseller_voice decimal,
	shared_hosting decimal,
	voice_connect decimal,
	voice_line decimal,
	others decimal,
	channel varchar,
	CONSTRAINT pkey_source_colt_customers_id PRIMARY KEY (id) 
);