CREATE TABLE client.network_nodes
(
	id serial,
	lat double precision,
	lon double precision,
	node_type varchar,
	geog geography('POINT', 4326),
	CONSTRAINT network_nodes_pkey PRIMARY KEY (id)
);

SELECT AddGeometryColumn('client', 'network_nodes', 'geom', 4326, 'POINT', 2);


-- Add the CO FOR VERIZON DEMO ONLY
-- Network nodes will now be added manually by the user or generated by the planning algorithms.
INSERT INTO client.network_nodes (node_type, geog, geom)
	SELECT
		'central_office',
		Geography(ST_Centroid(wirecenters.geom))as geog,
		ST_Centroid(wirecenters.geom) as geom
		
	FROM
		aro.wirecenters
	WHERE
		wirecenters.wirecenter = 'NYCMNY79';


CREATE INDEX client_network_nodes_geom_gist ON client.network_nodes USING gist (geom);
CREATE INDEX client_network_nodes_geog_gist ON client.network_nodes USING gist (geog);