###################
# default ETL
###################

reset_default:

etl_default: 
	default/etl.sh

###################
# Main ETL
###################

reset: reset_default 
load: etl_default

etl_reload_all: reset load


