version: '2'

services:
    db:
        image: postgis/postgis:12-3.0
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: aro
            POSTGRES_USER: aro
        command: postgres -c 'max_connections=200'
        # command: postgres -c log_statement=all
        networks:
            - main

    rabbitmq:
        image: rabbitmq:management
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - main

    service:
        image: avco/aro-service:latest
        build: ../../aro-service/docker
        ports:
            - "8888:8080"
        expose:
            - "8080"
        links:
            - db:arodb
            - zookeeper
            - rabbitmq
        environment:
            _JAVA_OPTS: "-Xms512m -Xmx1g"
            PGUSER: aro
            PGPASSWORD: aro
            PGDATABASE: aro
            PGHOST: arodb
            ARO_THREAD_COUNT: 5
            IGNITE_PROFILE: ignite_debug
            ZK_HOST: zookeeper
            RABBITMQ_HOST: rabbitmq
        networks:
            - main

    zookeeper:
        image: zookeeper
        ports:
            - "2181:2181"
        networks:
            - main

    app:
        image: avco/aro-app-base:node10-dev
        container_name: docker_app_1
        volumes:
            - ..:/srv/www/aro
            - ../../aro-etl:/srv/www/aro/db
            - ../../aro-data:/srv/www/aro/data
        ports:
            - "8000:8000"
            - "9229:9229"
        links:
            - db:arodb
            - service:aro-service
        environment:
            NODE_ENV: development
            PGHOST: arodb
            PGPASSWORD: aro
            PGUSER: aro
            PGDATABASE: aro
            ARO_DATA_ROOT: /srv/www/aro/data
            DATABASE_URL: postgres://aro:aro@arodb/aro
            ARO_CLIENT: aro
            RAILS_ENV: development
            # GOOGLE_MAPS_API_KEY: replace-and-uncomment
            # GOOGLE_MAPS_API_IP_KEY: replace-and-uncomment
            # # Uncomment next line to fix janky scroll-zoom mouse behavior:
            # GOOGLE_MAPS_GESTURE_HANDLING: cooperative
            # ARO_SERVICE_URL: http://docker.for.mac.localhost:8080
            # GOOGLE_MAPS_GESTURE_HANDLING: auto
            # MABL_TESTING: true
            LOGGER_EXCLUDES: >
                ["MAP_SET_ARE_TILES_RENDERING", "PLAN_UPDATE_DEFAULT_PLAN_COORDINATES"]
        working_dir: /srv/www/aro
        command: bash -c "/usr/sbin/sshd -D"
        networks:
            - main

    # reportsrv:
    #     image: avco/aro-reportsrv
    #     container_name: docker_reportsrv_1
    #     command: bash -c "cd /app && npm install && ./node_modules/.bin/nodemon --inspect=0.0.0.0:9230"
    #     ports:
    #         - "7000:7000"
    #         - "9230:9230"
    #     # environment:
    #     #     APP_BASE_URL: http://localhost:8000
    #     volumes:
    #         - ../../aro-reportsrv:/app
    #     networks:
    #         - main

    # # Uncomment the container below if you want to run the PG Admin server
    # pgadmin:
    #     image: dpage/pgadmin4
    #     ports:
    #       - "8082:80"
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: [your.name]@altmansolon.com
    #         PGADMIN_DEFAULT_PASSWORD: password

volumes:
    postgres-data:
        driver: local

networks:
    main:
        name: main
