version: '2'

services:
    db:
        image: 976168524097.dkr.ecr.us-east-1.amazonaws.com/aro/aro-postgis:10
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: aro
            POSTGRES_USER: aro
    rabbitmq:
        image: rabbitmq:management
        ports:
            - "5672:5672"
            - "15672:15672"
            - "41452:41452"
            - "33562:33562"
    service:
        image: 976168524097.dkr.ecr.us-east-1.amazonaws.com/aro/aro-service:latest
        expose:
            - "8080"
        links:
            - db:arodb
            - zookeeper
        environment:
            _JAVA_OPTS: "-Xms512m -Xmx1g"
            PGUSER: aro
            PGPASSWORD: aro
            PGDATABASE: aro
            PGHOST: arodb
            ARO_THREAD_COUNT: 5
            IGNITE_PROFILE: ignite_debug
            ZK_HOST: zookeeper
    zookeeper:
        image: zookeeper

    app:
        image: 976168524097.dkr.ecr.us-east-1.amazonaws.com/aro/aro-app-base-dev:latest
        volumes:
            - ..:/srv/www/aro
            - ../../aro-etl:/srv/www/aro/db
            - ../../aro-data:/srv/www/aro/data
        ports:
            - "8000:8000"
        links:
            - db:arodb
            - service:aro-service
        environment:
            PGHOST: arodb
            PGPASSWORD: aro
            PGUSER: aro
            PGDATABASE: aro
            ARO_DATA_ROOT: /srv/www/aro/data
            DATABASE_URL: postgres://aro:aro@arodb/aro
            ARO_CLIENT: aro
            RAILS_ENV: development
        working_dir: /srv/www/aro
        command: bash -c "/usr/sbin/sshd -D"

    # Uncomment the container below if you want to run the PG Admin server
    # pgadmin:
    #     image: dpage/pgadmin4
    #     ports:
    #       - "8082:80"
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: parag@metronconsulting.com
    #         PGADMIN_DEFAULT_PASSWORD: changeMePlease

volumes:
    postgres-data:
        driver: local



