version: '2'

services:
    db:
        image: mdillon/postgis:9.5
        volumes:
            - postgres-data-02:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: aro
            POSTGRES_USER: aro
    service:
        image: ait-docker-registry.cloud.altvil.com/aro-service
        expose:
            - "8080"
        links:
            - db:arodb
        environment:
            CATALINA_OPTS: -Xmx1g
            PGUSER: aro
            PGPASSWORD: aro
            PGDATABASE: aro
            PGHOST: arodb
            ARO_THREAD_COUNT: 5
    app:
        image: ait-docker-registry.cloud.altvil.com/aro/aro-app-base-dev:latest
        volumes:
            - ..:/srv/www/aro
            - ../../aro-etl:/srv/www/aro/db
        ports:
            - "8000:8000"
        links:
            - db:arodb
            - service:aro-service
        environment:
            PGHOST: arodb
            PGPASSWORD: aro
            PGUSER: aro
            PGDATABASE: aro
            ARO_DATA_ROOT: /srv/www/aro/db/data
            DATABASE_URL: postgres://aro:aro@arodb/aro
            ARO_CLIENT: aro
        working_dir: /srv/www/aro
        command: bash -c "/usr/sbin/sshd -D"


volumes:
    postgres-data-02:
        driver: local



