version: '2'

services:
    db:
        image: ait-docker-registry.cloud.altvil.com/aro/aro-postgis:9.5
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: aro
            POSTGRES_USER: aro
    service:
        image: ait-docker-registry.cloud.altvil.com/aro/aro-service:latest
        expose:
            - "8080"
        links:
            - db:arodb
            - zookeeper
        environment:
            _JAVA_OPTS: "-Xms512m -Xmx1g"
            PGUSER: aro
            PGPASSWORD: aro
            PGDATABASE: aro
            PGHOST: arodb
            ARO_THREAD_COUNT: 5
            IGNITE_PROFILE: ignite_debug
            ZK_HOST: zookeeper

     zookeeper:
        image: zookeeper
    app:
        image: ait-docker-registry.cloud.altvil.com/aro/aro-app-base-dev:latest
        volumes:
            - ..:/srv/www/aro
            - ../../aro-etl:/srv/www/aro/db
            - ../../aro-data:/srv/www/aro/data
            - ../../aro-data-vz:/srv/www/aro/data/private
        ports:
            - "8000:8000"
        links:
            - db:arodb
            - service:aro-service
        environment:
            PGHOST: arodb
            PGPASSWORD: aro
            PGUSER: aro
            PGDATABASE: aro
            ARO_DATA_ROOT: /srv/www/aro/data
            DATABASE_URL: postgres://aro:aro@arodb/aro
            ARO_CLIENT: aro
            RAILS_ENV: development
        working_dir: /srv/www/aro
        command: bash -c "/usr/sbin/sshd -D"


volumes:
    postgres-data:
        driver: local



