version: '2'

services:
    db:
        image: mdillon/postgis:9.5
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: aro
            POSTGRES_USER: aro
    app:
        image: ait-docker-registry.cloud.altvil.com/aro/aro-app-base-dev:latest
        volumes:
            - ..:/srv/www/aro
            - ../../aro-etl:/srv/www/aro/etl
        ports:
            - "8000:8000"
        links:
            - db:arodb
        environment:
            PGHOST: arodb
            PGPASSWORD: aro
            PGUSER: aro
            PGDATABASE: aro
            ARO_DATA_ROOT: /srv/www/aro/etl/data
            DATABASE_URL: postgres://aro:aro@arodb/aro
            ARO_CLIENT: aro
        working_dir: /srv/www/aro

volumes:
    postgres-data:
        driver: local



