FROM aro-ignite-jdk8
MAINTAINER Altvil
ENV PGUSER=${PGUSER}
ENV PGPASSWORD=${PGPASSWORD}
ENV PGHOST=${PGHOST}
ENV PGDATABASE=${PGDATABASE}
ADD aroServlet-igniteConfig-abstract.xml aroServlet-igniteConfig-abstract.xml
ADD aroServlet-igniteConfig.xml aroServlet-igniteConfig.xml

