FROM apacheignite/ignite:1.5.0.final
MAINTAINER Altvil
ENV PGUSER=${PGUSER}
ENV PGPASSWORD=${PGPASSWORD}
ENV PGHOST=${PGHOST}
ENV PGDATABASE=${PGDATABASE}
ADD aroServlet-igniteConfig.xml aroServlet-igniteConfig.xml

