FROM aro-ignite-jdk8
MAINTAINER Altvil
ENV PGUSER=${PGUSER}
ENV PGPASSWORD=${PGPASSWORD}
ENV PGHOST=${PGHOST}
ENV PGDATABASE=${PGDATABASE}
ADD igniteConfig-abstract.xml igniteConfig-abstract.xml
ADD igniteConfig-basicNode-docker.xml igniteConfig-basicNode-docker.xml

