DROP TABLE IF EXISTS client.network_nodes;

CREATE TABLE client.network_nodes
(
	id serial,
	lat double precision,
	lon double precision,
	node_type_id int references client.network_node_types,
	geog geography('POINT', 4326),
	CONSTRAINT network_nodes_pkey PRIMARY KEY (id)
);

SELECT AddGeometryColumn('client', 'network_nodes', 'geom', 4326, 'POINT', 2);


-- Add COs provided in source_colt.locations table
-- Using this as source of all COs in Frankfurt and Paris for now,
-- because we have not been provided lat/long pairs for the list in Paris, and the data is not 
-- consistent enough between Paris/Frankfurt to make it worthwhile to import the source data at this oint.

-- Network nodes will now be added manually by the user or generated by the planning algorithms.
INSERT INTO client.network_nodes (node_type_id, geog, geom)
	SELECT DISTINCT ON (bm_building_id)
		(select t.id from client.network_node_types t where name = 'central_office' limit 1)::int, 
		ST_SetSRID(ST_Point(ad_longitude, ad_latitude),4326)::geography as geog,
		ST_SetSRID(ST_Point(ad_longitude, ad_latitude),4326) as geom
		
	FROM
		source_colt.locations
	WHERE
	   bm_building_category = 'Central Office'
    ;



CREATE INDEX client_network_nodes_geom_gist ON client.network_nodes USING gist (geom);
CREATE INDEX client_network_nodes_geog_gist ON client.network_nodes USING gist (geog);